config/routes.rb
Rails.application.routes.draw do
  resources :compras
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "compras#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/compra.rb
class Compra < ApplicationRecord
    self.per_page = 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: %i[ show edit update destroy ]

  # GET /compras or /compras.json
  def index
    @compras = Compra.paginate(page: params[:page])
  end

  # GET /compras/1 or /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras or /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to compra_url(@compra), notice: "Compra was successfully created." }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1 or /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to compra_url(@compra), notice: "Compra was successfully updated." }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1 or /compras/1.json
  def destroy
    @compra.destroy

    respond_to do |format|
      format.html { redirect_to compras_url, notice: "Compra was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def compra_params
      params.require(:compra).permit(:name, :data, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/compras/_compra.html.erb
<div id="<%= dom_id compra %>">
  <p>
    <strong>Name:</strong>
    <%= compra.name %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= compra.data %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= compra.price %>
  </p>

</div>

app/views/compras/_form.html.erb
<%= form_with(model: compra) do |form| %>
  <% if compra.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
        <% compra.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.datetime_field :data %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing compra</h1>

<%= render "form", compra: @compra %>

<br>

<div>
  <%= link_to "Show this compra", @compra %> |
  <%= link_to "Back to compras", compras_path %>
</div>

app/views/compras/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Compras</h1>
<%= will_paginate @compras %>

<div id="compras">
  <% @compras.each do |compra| %>
    <%= render compra %>
    <p>
      <%= link_to "Show this compra", compra %>
    </p>
  <% end %>
</div>

<%= link_to "New compra", new_compra_path %>

app/views/compras/new.html.erb
<h1>New compra</h1>

<%= render "form", compra: @compra %>

<br>

<div>
  <%= link_to "Back to compras", compras_path %>
</div>

app/views/compras/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @compra %>

<div>
  <%= link_to "Edit this compra", edit_compra_path(@compra) %> |
  <%= link_to "Back to compras", compras_path %>

  <%= button_to "Destroy this compra", @compra, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pagination</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>